### ISSUE TITLE
Pawns hoard weapons listed in loadout.

### ISSUE THREAD

**Issue by KILLAKAN10** [CombatExtendedRWMod/CombatExtended#1205] opened 2020-04-08 12:05 UTC
Replicated behavior in world with just the main three mods (CE, guns and melee), I don't really know how to detail it any further, some pawns behave, others will just grab all the bolt action rifles they can hold.

**Comment by N7Huntsman** [comment] 2020-04-08 15:55
It's a known issue associated with the 'Any Medicine' option in loadouts. Put the weapon above that in the loadout list, and it shouldn't happen.

**Comment by KILLAKAN10** [comment] 2020-04-09 02:33
What the hell?
That is, absolutely fascinating, 

Thing is, I don't remember doing that, but I'll see if I am and I'll report back

**Comment by N7Huntsman** [comment] 2020-04-10 04:17
Duplicate of #1181

**Closed by N7Huntsman** 2020-04-10 04:17 UTC
